sudo: required
language: ruby
services:
  - docker
before_install:
  - docker pull kamaradclimber/mesos-modules-ruby-ci
  - docker run --mount type=bind,source="$(pwd)",target=/app kamaradclimber/mesos-modules-ruby-ci /bin/bash -c 'cd /app && export MESOS_BUILD_DIR=/root/rpmbuild/BUILD/mesos-1.4.0/ && cmake . && make && make check'

script:
  - /bin/true
